# Generated by Django 4.1 on 2022-08-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
