# Generated by Django 4.1 on 2022-08-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='stop',
        ),
    ]
