# Generated by Django 4.1 on 2022-08-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='saved',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
