# Generated by Django 4.1 on 2022-08-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_entry_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='saved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
