# Generated by Django 4.1 on 2022-08-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='project',
        ),
    ]
