# Generated by Django 4.1 on 2022-08-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.task'),
        ),
    ]
